# SITE CONFIGURATION
baseurl: ""
url: "http://JasonMadeSomething.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Jason Teitelman 
  description: "Jason Teitelman's Programming Portfolio" 

  # Header and footer text
  header_text: >
     <h1>I would rather be coding</h1>
     <p>I'm a neophyte programmer itching to solve problems.</p>
  header_text_feature_image: 
  footer_text: >
   Shamelessly powered by <a href="http://jekyllrb.com">Jekyll</a> and made with the Kami template.

  # Icons
  rss: false
  email_address: "jason@mailmarketingfla.com"
  behance:
  bitbucket:
  dribbble: 
  facebook: 
  flickr:
  github: "jasonMadeSomething"
  google_plus:
  instagram: 
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "http://stackexchange.com/users/5955032/soviet-jesus"
  steam: 
  tumblr:
  twitter: 
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-79264636-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
